### ISSUE TITLE
cookie-consent: Fix outlink tracking

### ISSUE THREAD

**Issue by michaelwood** [ThreeSixtyGiving/360-ds#79]
Fix outlink tracking: https://github.com/ThreeSixtyGiving/360-ds/commit/de307c87b0eeba4d5ab8f673783f0e73b5ff613c

Non-odsc:
- [x] Website
- [x] Covidtracker

PRs

- [x] Grantnav - https://github.com/ThreeSixtyGiving/grantnav/pull/848
- [x] Insights - https://github.com/ThreeSixtyGiving/insights-ng/pull/152
- [x] Registry - https://github.com/ThreeSixtyGiving/registry/pull/109
- [x] Dataquality - https://github.com/ThreeSixtyGiving/dataquality/pull/34
- [x] Quality dashboard - https://github.com/ThreeSixtyGiving/registry/commit/a6130b305fb4abdcebb9ebead08e422fec7d5cab

Deploy
- [x] Grantnav 
- [x] Insights 
- [x] Registry
- [x] Dataquality 
- [x] Quality dashboard

**Comment by michaelwood** [comment]
(Dataquality is pending review)
